version: '3.4'
services:
  influxdb:
    restart: always
    image: influxdb:1.8
    network_mode: "host"
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=1234
      - INFLUXDB_USER=telegraf-username
      - INFLUXDB_USER_PASSWORD=telegraf-password
  mosquitto:
    restart: always
    image: eclipse-mosquitto:1.5
    network_mode: "host"
    hostname: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
  telegraf:
    restart: always
    image: telegraf:1.20
    network_mode: "host"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      
  grafana:
    restart: always
    image: grafana/grafana
    network_mode: "host"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  influxdb-storage:
