{
 "title": "Aktuelle Werte",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"/public/images/kitLogo.png\"></img>\n\n\n"
   },
   "content": "<img src=\"/public/img/kitLogo.png\"></img>\n\n<style>\n.panel-title-text {\n font-size: large;\n}\n</style>\n\n"
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 0 },
   "options": {
    "content": " <center><h1>IEH-Wetterstation</h1></center> \n"
   },
   "content": " <center><h1>IEH-Wetterstation</h1></center> \n"
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": {
    "content": "<img src=\"/public/images/iehLogo.png\"></img>\n\n"
   },
   "content": "<img src=\"/public/img/iehLogo.png\"></img>\n\n"
  },
  {
   "title": "Temperatur",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 4 },
   "format": "celsius",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"temperature\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sensors') GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 4 },
   "format": "pressurehpa",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"pressure\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sensors') GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luftfeuchte",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 4 },
   "format": "humidity",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"humidity\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sensors') GROUP BY *ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}